### PR TITLE
fix #18: Final Answer should not use JSON

### LINKED ISSUE #18: Final Answer should not use JSON
Final Answer should not use JSON. I asked it to "Write a snake game," and the thought process was correct, but at the Final answer stage:

Failed to generate final answer after 3 attempts. Error: Error code: 400 - {'error': {'message': "Failed to generate JSON. Please adjust your prompt. See 'failed_generation' for more details.", 'type': 'invalid_request_error', 'code': 'json_validate_failed', 'failed_generation': '{"title": "Final Answer: Snake Game Implementation", "content": "Here is a simple implementation of the snake game in Python using Pygame:\n\n```python\nimport pygame\nimport sys\nimport random\n\n# Initialize Pygame\npygame.init()\n\n# Set up some constants\nWIDTH, HEIGHT = 800, 600\nSPEED = 10\nBLOCK_SIZE = 20\n\n# Set up some colors\nWHITE = (255, 255, 255)\nRED = (255, 0, 0)\nGREEN = (0, 255, 0)\n\n# Set up the display\nscreen = pygame.display.set_mode((WIDTH, HEIGHT))\n\n# Set up the font\nfont = pygame.font.Font(None, 36)\n\n# Set up the snake and food\nsnake = [(200, 200), (220, 200), (240, 200)]\nfood = (400, 300)\n\n# Set up the direction\ndirection = 'right'\n\n# Game loop'}}

### PR DESCRIPTION
**Pull request by JerryYin777**
Fix issue #16 and #18 : Final answer does not need to use JSON formatting

Now the bug example is bug free, I also add a code renderer via streamlit:

For example in #16:

image
image
image

For example in #18 

image
image

Let me know if you have any other questions and bugs.

### CODE REVIEW

**Review by bklieger-groq — CHANGES_REQUESTED** [review]
Instead of modifying the original prompt, let's have a new prompt that is used for generating the final answer. This will allow us to include instructions specific to the final answer generation without impacting the reasoning step generation.

Can you make the modification requested? Specifically, instead of adding new lines to the current system prompt, create logic to swap the system prompt when "is_final_answer" is true for a different final answer prompt that includes instructions to not use JSON formatting. This approach will give us more flexibility in the future and modularize the functionality.

**Comment by bklieger-groq** [comment]
Great job! I have requested one change above. Could you also change the request to merge into the `develop` branch instead of `main`? Thank you!

**Comment by JerryYin777** [comment]
Sure! Actually, we do not need to change the given prompt (sry it's my fault), and I have revised `max_token` to the original (200) too.

image

I've changed my code, if there are any other problems, let me know

**Review by bklieger-groq — APPROVED** [review]

**Comment by bklieger-groq** [comment]
Merged. Thank you for your contribution!

**Pull request merged**
