### PR TITLE
added a Huggingface space demo

### PR DESCRIPTION
**Pull request by jpgodfan**
i deployed the gradio app in huggingface spaces with adding 2 modes, "public" and "private", the "public" mode uses a free pre-configured groq API key, so anyone can access and chat with g1 publically without entering it's own groq API key, but incase of reaching api request limits and usage limits of the pre-configured public API key you can switch to "private" mode wich will show an input to input your own and private groq API key and use it (like original gradio app).

By the way, used Huggingface space demo is [here](https://huggingface.co/spaces/xylin/g1-demo)

### CODE REVIEW

**Comment by bklieger-groq** [comment]
Great! Can you move the link to the "Top Forks" section instead of adding a new section to the README? Since the code was modified, and is not automatically updated from this repository, it is best described as a fork. 

After completing that change, I will approve the PR.

**Comment by jpgodfan** [comment]
so i will add the repository link with Huggingface space demo link in the "Top Forks" Section ?

**Comment by jpgodfan** [comment]
done, i moved the Huggingface spaces demo to "Top forks" section instead of the previous place

**Review by bklieger-groq — APPROVED** [review]

**Comment by jpgodfan** [comment]
can be merged to the "main" branch ?

**Comment by bklieger-groq** [comment]
When develop is merged to main on the next release, it will be there!

**Comment by jpgodfan** [comment]
ok, thank you, and i appreciate that you accepted my contribution

**Pull request merged**
