### PR TITLE
Ollama Implementation.

### PR DESCRIPTION
**Pull request by hidden1nin**
I have added ollama implementation in a new file named ollama_app.py

### CODE REVIEW

**Comment by hidden1nin** [comment]
I can make any edits needed.

**Review by bklieger-groq — CHANGES_REQUESTED** [review]
This is great! Can you move this file to a new folder named "ollama"? Then I will finish the review and merge. I would like to keep the root folder clean with just one app.py. 

As a side note, eventually, if the g1 code becomes repetitive, it could make sense to turn g1 into a library of functions and providers.

**Comment by hidden1nin** [comment]
I have moved the file to a folder :)

**Review by bklieger-groq — CHANGES_REQUESTED** [review]
Thank you for the changes! Please also remove the __pycache__ from the PR and add an updated requirements.txt in the ollama folder that includes ollama instead of groq. See the gradio folder for an example if needed.

**Comment by hidden1nin** [comment]
Should be up to date now and with the fixes requested.

**Comment by bklieger-groq** [comment]
Great job, thank you! Merged.

**Pull request merged**
